### ISSUE TITLE
数据少时，滑动一下跳跃大

### ISSUE THREAD

**Issue by wstcLi** [cslmark/SLCurveChartLib#11]
麻烦帮忙看下我遇到的这个问题，谢谢。在数据少时，向右滑动直接跳到右侧，可不可以不跳跃
<img width="333" alt="20cfa472-90fe-4f29-8223-be81f189b670" src="https://user-images.githubusercontent.com/29402955/28398819-8eec79ec-6d3b-11e7-8baa-b9d57ba5851c.png">
<img width="338" alt="cee67747-ac79-4f83-848c-61d280c33d68" src="https://user-images.githubusercontent.com/29402955/28398822-9525307e-6d3b-11e7-89be-aab4de080ca1.png">
<img width="339" alt="ce8d7428-846c-40b6-8c7f-38d78d19e6d7" src="https://user-images.githubusercontent.com/29402955/28398825-9c952ee0-6d3b-11e7-99c1-ed25d8dc1774.png">
<img width="342" alt="8e13a996-c49b-4dc3-9758-87365ffa1cb0" src="https://user-images.githubusercontent.com/29402955/28398830-a2a34a56-6d3b-11e7-86d9-2f421b910157.png">

**Comment by cslmark** [comment]
Sorry，最近事情多，心情不大好。没及时把你解决。。你想做到的是数据少的时候无法滑动，还是其他的怎么说？

**Comment by wstcLi** [comment]
我自己改了一下，可以使用了，谢谢哈

**Comment by cslmark** [comment]
呵呵。。。厉害！不过可以告知我你需要的效果是什么样的吗，我也修改下，之前没有考虑到数据这么少的情况

**Comment by cslmark** [comment]
@wstcLi OK!已经在最新的分支上提交了  “mulcurDev”提交了修改方案，即数据量很少的时候不能滑动。放大之后依然可以滑动，刚好也改了xright的一个step的小bug,谢谢你，让我发现了bug！

**Comment by wstcLi** [comment]
我看了你的修改，是我想要做的效果，谢谢，我想要的效果还包括初始的时候选中最后一个点，且默认显示最后部分，如图，已完成，还是多谢你。
![4c2020ff4c4722441b58973f213e5e9d](https://user-images.githubusercontent.com/29402955/28706201-ca4724ea-73a5-11e7-8fdf-67fbc1db6739.png)

**Comment by cslmark** [comment]
OK，不过有一个小bug你如果有用到该属性需要注意下，就是算右边距的时候   并不是 xstep*datasoure.count 而是  xstep*（datasource.count - 1），否则右边距会是 xright+xstep，多了一个step,也就是5个点之间距离是4。（今天提交的已经把这个问题解决了）

**Comment by wstcLi** [comment]
恩恩，看到你修改的了。

**Comment by lvyongtao** [comment]
你好 怎么处理默认显示最后的部分@wstcLi

**Comment by wstcLi** [comment]
![cccca346-c4e1-4c67-8a9c-e838cdec0357](https://user-images.githubusercontent.com/29402955/29021879-a1e9cd08-7b99-11e7-854d-20010b20e40d.png)
@lvyongtao
