### ISSUE TITLE
当x对应的所有y值为0时，线没有画出来。

### ISSUE THREAD

**Issue by anselPeng** [cslmark/SLCurveChartLib#12]
当x对应的所有y值为0时，线没有画出来。并且报出2个error：
1:CGContextAddLineToPoint: no current point。
2:Error: this application, or a library it uses, has passed an invalid numeric value (NaN, or not-a-number) to CoreGraphics API and this value is being ignored. Please fix this problem.

**Comment by cslmark** [comment]
OK，So sorry to hear that, 等我工作稳定了，会改好这个问题，并且给你答复！

**Comment by anselPeng** [comment]
OK 感谢

**Comment by cslmark** [comment]
特别抱歉，那么久才给你回复。我这边试了一下，曲线中0的点是会画出来的。如果不行，你可以同步下mulCur分支
