### ISSUE TITLE
折线图的坐标点空心圆点，外环和内圆的圆心对不齐，这个问题有人解决吗？谢谢

### ISSUE THREAD

**Issue by zhaowenhao0213** [cslmark/SLCurveChartLib#14]
折线图的坐标点空心圆点，外环和内圆的圆心对不齐，这个问题有人解决吗？谢谢

**Comment by cslmark** [comment]
嗯，这个问题我有空的时候看下

**Comment by cslmark** [comment]
这个问题解决了，请同步下mulcurDev这个分支，产生的原因是以下参数类型定义，原来定义为int,所以会中点误差，你可以直接如下图修改，都改为CGFloat这个问题就解决了，
![image](https://user-images.githubusercontent.com/13198159/37381420-0e3ce1a4-2778-11e8-8d2a-db1b37ee40d7.png)
文件所在的目录如下，感谢你的使用
![image](https://user-images.githubusercontent.com/13198159/37381448-3797ca6e-2778-11e8-9b80-10f4b4c1e497.png)

**Comment by zhaowenhao0213** [comment]
谢谢帮助 ，已经完美解决，学到很多
