### ISSUE TITLE
怎么绘制折线下方区域的渐变色

### ISSUE THREAD

**Issue by wstcLi** [cslmark/SLCurveChartLib#3]

**Comment by cslmark** [comment]
加一个渐变区域倒也容易，目前没有这种功能！你们一般需要的渐变区域是什么样子的呀，大概那些方便提供接口出来可配置是你们需求需要的

**Comment by wstcLi** [comment]
沿着折线向下的区域图,就像charts里那样的效果
charts填充折线下方区域颜色
![ca969ee4-804e-4cb0-a91f-416ed6a8affe](https://user-images.githubusercontent.com/29402955/27427238-ce8e5240-5770-11e7-9e89-6f85e9128fda.png)
相关代码：//第一种填充样式:单色填充 // set1.drawFilledEnabled = YES;//是否填充颜色 // set1.fillColor = [UIColor redColor];//填充颜色 // set1.fillAlpha = 0.3;//填充颜色的透明度 //第二种填充样式:渐变填充 set1.drawFilledEnabled = YES;//是否填充颜色 NSArray *gradientColors = @[(id)[ChartColorTemplates colorFromString:@"#FFFFFFFF"].CGColor, (id)[ChartColorTemplates colorFromString:@"#FF007FFF"].CGColor]; CGGradientRef gradientRef = CGGradientCreateWithColors(nil, (CFArrayRef)gradientColors, nil); set1.fillAlpha = 0.3f;//透明度 set1.fill = [ChartFill fillWithLinearGradient:gradientRef angle:90.0f];//赋值填充颜色对象 CGGradientRelease(gradientRef);//释放gradientRef //点击选中拐点的交互样式

**Comment by wstcLi** [comment]
还有一个体验上的现象，数据少且缩到很密集的时候，滑动会出现整体位置跳动的情况

**Comment by cslmark** [comment]
已经更新了内容，增加了渐变色，属性有四个个 drawFilledEnabled  fillColor gradientColors lineFillMode模式选择，没有采纳你时候的fillAlpha，因为颜色数值本身就就有透明度，没必要额外属性。 体验上的问题，我有时间再看看！

**Comment by popking5466** [comment]
去哪里下载有渐变功能的代码?

**Comment by popking5466** [comment]
请问在哪里可以下载到渐变色的代码?1.0.3好像还没有这个功能

**Comment by popking5466** [comment]
dataSet.gradientColors = @[[UIColor whiteColor], [UIColor clearColor]];
为什么白色会出问题,好像是白色 = 透明

**Comment by popking5466** [comment]
#pragma mark - 当数据源发生了改变的时候，采用该方法进行调用
-(void) refreashDataSourceRestoreContext:(SLLineChartData*) datasource{
    _datasource = datasource;
    self.backgroundColor = [datasource graphColor];
    self.backgroundColor = [UIColor clearColor];
    
    
    
    
    //初始化CAGradientlayer对象，使它的大小为UIView的大小
    _gradientLayer  = [CAGradientLayer layer];
    _gradientLayer .frame = self.bounds;
    
    //将CAGradientlayer对象添加在我们要设置背景色的视图的layer层
    
//    [self.layer addSublayer:_gradientLayer];
    [self.layer insertSublayer:_gradientLayer atIndex:0];
    //设置渐变区域的起始和终止位置（范围为0-1）
    _gradientLayer .startPoint = CGPointMake(0, 0);
    _gradientLayer .endPoint = CGPointMake(1, 0);
    
    //设置颜色数组
    _gradientLayer .colors = @[(__bridge id)Rgb2UIColor(129, 225, 132).CGColor,
                               (__bridge id)Rgb2UIColor(70, 215, 152).CGColor];
    
    
    //完全重新更新
    [self setup];
    [self refreashGraph];
}
改变不了渐变背景色有点尴尬

**Comment by cslmark** [comment]
你想把背景色变成什么样子的呢，渐变图层clearColor我没有试过，还有要渐变色的，请同步github上的分支，mulCurDev。。。。可以代码clone下来之后使用一下命令checkout, git的使用任何问题可以参考我的简书:http://www.jianshu.com/p/5da935d82b22
$ git checkout -b dev origin/dev
两个人同时对于同一分支进行了修改 比如:origin/dev分支,可以通过以下命令来解决
git pull
git pull如果也还是失败，有可能是因为本地dev分支与远程origin/dev分支的链接
$ git branch --set-upstream dev origin/dev

**Comment by cslmark** [comment]
改变整个图标的背景颜色
1.没必要这么复杂，除非你要添加渐变这个功能没有，    
   NSMutableArray* tempArray = [NSMutableArray arrayWithCapacity:1];
    [tempArray addObject:dataSet];
    [tempArray addObject:dataSet2];
    SLLineChartData* dataSource = [[SLLineChartData alloc] initWithValues:tempArray];
    self.dataSource = dataSource;
    dataSource.graphColor = [UIColor blackColor];    //这样就直接可以改变背景色
2.关于你提的白色渐变色不行，我想应该不是渐变色不起作用，主要是因为。不同的背景色，显示效果可能不明显，比如在 灰色背景   red-clear可以很清晰的看到， 但是在 黑色背景  那么 red-clear的渐变效果就看不到。。。不太建议直接使用clearColor主要是我的渐变是整个图表。。。当绝大多数的数据处于曲线图下端，可能你看到就是clearColor所以看起就没有效果了

**Comment by cslmark** [comment]
如果想看到明显的效果，其实也容易，直接把渐变图层的区域，直接从每个曲线图的最高点渐变到底即可。。不了解大家需求，目前是是直接从整个曲线图顶端，渐变到低部的。。。
需要调整，请回复！！！

**Comment by popking5466** [comment]
我知道您的意思,折线图下方的渐变色我已经通过您代码的分支实现,我目前需要的效果是,背景色也是渐变的,就好比您的那段"dataSource.graphColor = [UIColor blackColor]; //这样就直接可以改变背景色",我需要的是blackColor是一个渐变色,所以,我通过添加了_gradientLayer 在BaseCurveView.m的第216行代码附近,但是添加上去的layer好像把Chart图层都挡住了,,尽管我已经用//    [self.layer insertSublayer:_gradientLayer atIndex:0];
 加到了最底层,您可以将我的代码复制到您的项目,然后跑起来试一试:
把您原始的215行代码:#pragma mark - 当数据源发生了改变的时候，采用该方法进行调用
-(void) refreashDataSourceRestoreContext:(SLLineChartData*) datasource;
替换成:
#pragma mark - 当数据源发生了改变的时候，采用该方法进行调用
-(void) refreashDataSourceRestoreContext:(SLLineChartData*) datasource{
    _datasource = datasource;
    self.backgroundColor = [datasource graphColor];
//    self.backgroundColor = [UIColor gre];
    
    
    
    
    //初始化CAGradientlayer对象，使它的大小为UIView的大小
    _gradientLayer  = [CAGradientLayer layer];
    _gradientLayer .frame = self.bounds;
    
    //将CAGradientlayer对象添加在我们要设置背景色的视图的layer层
    
//    [self.layer addSublayer:_gradientLayer];
//    [self.layer insertSublayer:_gradientLayer atIndex:0];
    //设置渐变区域的起始和终止位置（范围为0-1）
    _gradientLayer .startPoint = CGPointMake(0, 0);
    _gradientLayer .endPoint = CGPointMake(1, 0);
    
    //设置颜色数组
    _gradientLayer .colors = @[(__bridge id)Rgb2UIColor(129, 225, 132).CGColor,
                               (__bridge id)Rgb2UIColor(70, 215, 152).CGColor];
    
    
    //完全重新更新
    [self setup];
    [self refreashGraph];
}

**Comment by popking5466** [comment]
我还尝试,将dataSource.graphColor = [UIColor clearColor];
改成
dataSource.graphColor = [UIColor clearColor];
    [self.myView setBackgroundColor:[UIColor greenColor]];
也无法改变绿色,好像myview和basecurveview之间还有一层白色View

**Comment by popking5466** [comment]
至于是否从曲线最高层到底层,还是曲线图最高层到底层,我认为最好是有一个判断机制,如果可以实现就最好了,谢谢

**Comment by popking5466** [comment]
关于您提的这点:
2.关于你提的白色渐变色不行，我想应该不是渐变色不起作用，主要是因为。不同的背景色，显示效果可能不明显，比如在 灰色背景 red-clear可以很清晰的看到， 但是在 黑色背景 那么 red-clear的渐变效果就看不到。。。不太建议直接使用clearColor主要是我的渐变是整个图表。。。当绝大多数的数据处于曲线图下端，可能你看到就是clearColor所以看起就没有效果了
你可以尝试用(255, 255, 255 alpha : 1)的颜色去测试,白色会变得非常的明显,
但是[UIColor whiteColor]就是等同于透明

**Comment by cslmark** [comment]
First,你要背景变成渐变的颜色OK，这个也是很容易加，当然你直接加入渐变的图层显然不妥，加的位置也不对没因为你这个方法可能是经常会刷新的方法，要加也应该作为一个属性，添加在setup方法。并且保证唯一性。
Second,这个可以一个属性用于指示渐变的方式，不过考虑到属性太多反而让使用者难于理解，我想还是就默认从曲线的最高点默认渐变下来就好了。起码目前没有看到明显的弊端，而从曲线图最顶部往下渐变存在着clearColor看不到的问题
Third，背景颜色要实现渐变。。。这个建议把整个图表的背景颜色设置成clearColor, 然后把图表放到一个父视图，并将父视图设置成渐变。把背景搞成渐变色，最近没时间就先不加了。比如如下:
`- (void)viewDidLoad {
    [super viewDidLoad];
    
    CAGradientLayer* gradientLayer  = [CAGradientLayer layer];
    gradientLayer.frame = self.view.bounds;
    gradientLayer.startPoint = CGPointMake(0, 0);
    gradientLayer.endPoint = CGPointMake(0, 1);
    
    //设置颜色数组
    gradientLayer.colors = @[(__bridge id)[UIColor blueColor].CGColor,
                               (__bridge id)[UIColor greenColor].CGColor];
    [self.view.layer insertSublayer:gradientLayer atIndex:0];
    
    
    ChartAxisBase* xAxis = self.myView.XAxis;
    xAxis.axisValueFormatter = [[XAxisFormtter alloc] init];
    xAxis.drawLabelsEnabled = YES;
`
效果如下，希望能解决你的问题。
![wx20170628-095428](https://user-images.githubusercontent.com/13198159/27617253-cdd2da80-5be7-11e7-8742-76d03b754c0b.png)

**Comment by cslmark** [comment]
目前工作上时间有点紧，就先不不更新了，等有时间，将加入动画封装，可以把背景渐变的需求考虑在里面，还有柱状图添加。等等。。。敬请期待。

**Comment by popking5466** [comment]
谢谢!
