### ISSUE TITLE
设置填充颜色怎么写呢？

### ISSUE THREAD

**Issue by NengQuan** [cslmark/SLCurveChartLib#4]
我在项目中找不到drawfill方法，没有更新上来吗？

**Comment by cslmark** [comment]
请下载mulCurDev的分支。。。如果git使用上有任何不明白的地方，可以参考我的简书:http://www.jianshu.com/p/5da935d82b22, 你可以把代码先测试下来，然后pull分支 mulcurDev
$ git checkout -b dev origin/dev
两个人同时对于同一分支进行了修改 比如:origin/dev分支,可以通过以下命令来解决
git pull
git pull如果也还是失败，有可能是因为本地dev分支与远程origin/dev分支的链接
$ git branch --set-upstream dev origin/dev

**Comment by NengQuan** [comment]
这个填充颜色的版本，我pod就是1.03版本吧？另外就是如图
![image](https://user-images.githubusercontent.com/15306400/27570378-4e72f21e-5b30-11e7-8762-eb78450b4fbc.png)
我该怎么设置X坐标从最左边开始呢

**Comment by cslmark** [comment]
从x轴最左边开始会导致，圈圈显示不全。。。一定要从最左边开始，进入BaseCurView中的 step中中xleft变成0应该就可以了。。此外 cocoapod上使用的还是master分支. @NengQuan 
<img width="241" alt="wx20170627-124419 2x" src="https://user-images.githubusercontent.com/13198159/27571172-62f761c4-5b36-11e7-9808-9fdcfdaa6921.png">

`-(void) setup{
    xleft = 0;
    xright = 20;
    pointR = 4;
    ytop = 35;
    ybottom = 35;`

**Comment by NengQuan** [comment]
我还想问下，主题颜色怎么修改呢？我想改为clear color，不要黑色

**Comment by cslmark** [comment]
so Easy! 
<img width="241" alt="wx20170627-124419 2x" src="https://user-images.githubusercontent.com/13198159/27574556-7db3c1f2-5b49-11e7-9156-2e43b2d1763a.png">

**Comment by cslmark** [comment]
so Easy!
<img width="954" alt="wx20170627-145813 2x" src="https://user-images.githubusercontent.com/13198159/27574578-9f5e04d4-5b49-11e7-9d65-edf317f210ee.png">

**Comment by NengQuan** [comment]
真太谢谢楼主了！
![image](https://user-images.githubusercontent.com/15306400/27575135-5081c8a8-5b4b-11e7-9ecf-cf7ebefb15e3.png)
我们这边需求是这个 我找很久 找不到修改左边栏数据的地方

**Comment by NengQuan** [comment]
另外就是 
![image](https://user-images.githubusercontent.com/15306400/27576022-271f3600-5b4e-11e7-83a6-7e2179823038.png)
框架可以实现这个功能吗😭

**Comment by cslmark** [comment]
简单点来说，Easy一米。。。。。叫你一个特别简单的方法。。。
![image](https://user-images.githubusercontent.com/13198159/27578339-6a44c1b8-5b56-11e7-92a6-d9733e6568f7.png)
首先把以上的 6 改为 3 就会平均分成三等分。。。然后你 根据   vlaue的数值，可以再第一个代理方法中直接返回  
![image](https://user-images.githubusercontent.com/13198159/27578622-375a6644-5b57-11e7-8a2a-187d49de92ca.png)
不允许滚动，只需要数据 设置一个屏幕显示100个点，当前屏幕不超过100个点，就不能滚动了
![image](https://user-images.githubusercontent.com/13198159/27578707-70e95d20-5b57-11e7-9466-cd0ce660270d.png)

**Comment by NengQuan** [comment]
太谢谢楼主了！
