### ISSUE TITLE
请问怎么加快滑动速度呢

### ISSUE THREAD

**Issue by qiuseruxin** [cslmark/SLCurveChartLib#6]
我的数据量太大 4000条数据左右,现在的滑动速度太慢了

**Comment by cslmark** [comment]
请问。。。你一个屏幕显示多少个数据

**Comment by cslmark** [comment]
我这边测试，并没有出现滑动速度太慢的问题！

**Comment by qiuseruxin** [comment]
感谢您的回复,一个屏幕大概显示4000条数据左右,我是绘制用户血糖的曲线,我缩放缩到最小,从第一条数据滑动到最后一条数据的位置要用手滑动好久.....

**Comment by cslmark** [comment]
恕我直言一个屏幕显示4000条数据，恐怕没有不卡的。。。太多了，而且按照手机屏幕来说手机分辨率  640px,以iphone5为例子，如果4000个点，一个点连一个像素都不到，而且卡顿也正常 就算我绘制一个点需要 0.1ms 那么绘制4000个点就需要 0.4 估计Charts也该卡了。所以就算是绘制血糖，你也应该把一个屏幕绘制的点数改小，就算改小也就应该！

**Comment by qiuseruxin** [comment]
额 您可能误会了  我的意思我希望是手指滑一下,曲线左右滑动很大一块位置,这样我能更快的滑到最后一条数据.现在4000条数据目前我发现和200条数据移动的速度是一样的,并没有卡顿

**Comment by cslmark** [comment]
OK，明白你的意思了。这个功能目前不支持，待我研究下！有时间再更新吧！

**Comment by qiuseruxin** [comment]
感谢!

**Comment by qiuseruxin** [comment]
感谢我现在改了您 BaseCurveView 中  fromX -= translation.x 的值 现在滑动速度会变快,但是不知道会不会导致其他的BUG

**Comment by cslmark** [comment]
那个数值可以修改，但是直接修改可能不是特别好。最好的把速度考虑在里面。。BUG倒是不会出现！

**Comment by cslmark** [comment]
你好，最新的分支中引入了速度跟随功能。。。可以根据你们自己项目的需求去使能，加速效果和达到你说的滑动速度快的效果。。默认减速率为 50.0f 你可以根据自己的需要调整，该数值越小，减速的距离越长！

**Comment by cslmark** [comment]
距离加层部分请在这里改，目前加层方案是物理学的方式  vt+0.5at*t的方式
![image](https://user-images.githubusercontent.com/13198159/27770278-46bef526-5f6e-11e7-8bf9-edf1b7a25c1d.png)

**Comment by qiuseruxin** [comment]
感谢作者,现在基本上完美了,就是老一点的机型真机调试时,当缩放到最小的时候,即使只有100条数据,滑动也会卡顿,当放大后滑动非常流畅,不知道是什么原因,不过无伤大雅

**Comment by cslmark** [comment]
老机器到底是多老的机器呀？有可能是处理器不行吧！

**Comment by qiuseruxin** [comment]
请问 有什么办法可以让X轴显示字符串吗 我看您设的是double类型,我现在想在X轴显示当前时间,比如  11:49   12:03 这种

**Comment by cslmark** [comment]
简单的一米。。。。不晓得为什么，你们都不会用，可以参考这个issue
https://github.com/cslmark/SLCurveChartLib/issues/4

**Comment by qiuseruxin** [comment]
我已经迷失了 没看懂那个issue 大大助我
 ChartDataEntry* entry = [[ChartDataEntry alloc] initWithX:i y:obj.BSValue];
我看您是用这个方法设置横纵的值的,    我现在X轴想传字符串,比如 11:48 这样  到源码里去改 ,改了半天,越改报错越多...

**Comment by cslmark** [comment]
给你新建了一个issue，https://github.com/cslmark/SLCurveChartLib/issues/7  
大小姐如果还看不懂，我也要迷失了！

**Comment by qiuseruxin** [comment]
受教了!  我看了你给我讲的issue  然后这样实现的,这样做对吗大神
ChartDataEntry* entry = [[ChartDataEntry alloc] initWithX:obj.timeIndex  y:obj.BSValue];
  我这里面的X传了一个时间戳,然后在你告诉我的方法里把时间戳转换成字符串
-(NSString *) stringForValue:(double) value axis:(ChartAxisBase *) axis{
    _formatter = [[NSDateFormatter alloc]init];
    _formatter.dateFormat = @"hh:mm";
    _formatter.timeZone = [NSTimeZone timeZoneWithName:@"GMT+8"];
    NSString *str=[NSString stringWithFormat:@"%0.0lf",value];//时间戳
    NSTimeInterval time=[str doubleValue];
    NSDate *detaildate=[NSDate dateWithTimeIntervalSince1970:time];
    NSString *axisLabel = [_formatter stringFromDate: detaildate];
    return axisLabel;
}

**Comment by cslmark** [comment]
So smart you are! 使用的方法就是你想的这样。只要遵循对应的代理，任何对象都可以定义显示的格式！

**Comment by popking5466** [comment]
请问如何控制:
轻轻的网往右滑动一下,直接跳24格,也就是说往右滑动一天,并且能够控制滑动开始到滑动结束的时间?谢谢

**Comment by popking5466** [comment]
轻轻的网往右滑动一下,直接跳24格(小时),并且能够让他慢慢滑,控制速度,不要一瞬间就到了,要有滑动的动画效果?
因为你这个不是scrollView,所以不知道在什么地方控制
请麻烦解答下,谢谢

**Comment by popking5466** [comment]
请问如何实现这个效果:
轻轻的网往右滑动一下,直接跳24格(小时),并且能够让他慢慢滑,控制速度,不要一瞬间就到了,要有滑动的动画效果?
因为你这个不是scrollView,所以不知道在什么地方控制
请麻烦解答下,谢谢

**Comment by cslmark** [comment]
不太清楚你的描述，向右滑动一下就24格，你说的莫不是scrollerView里面的page功能，还有动画控制速度。。。什么样的需求呀。

**Comment by popking5466** [comment]
就是scroll view 里面的page功能,不是一点一点的滑动,而是一页一页翻动,在chart上,以24个x坐标单位为一页,一翻就是向左或者向右移动24个x单位,可以不需要动画控制速度,但是不要在一瞬间完成,要有一个滑动的动画效果不能看不清楚 " 是往左滑动还是往右滑动(瞬间到位的那种)"  
请问您明白我在说什么了吗?
并且是否可以实现

**Comment by cslmark** [comment]
知道你再说什么，你这是要模拟scrollerView的功能呀。我就一个问题，请问你的数据量大吗？目前这个曲线库，是没有刻意实现这个功能，但是如果你想用布置在scrollView上面，你看可以看下，我原来的曲线框架是否能符合你的要求:https://github.com/cslmark/SLStatisticsView
当然该库是全屏绘制的形式，如果数据量太大，缩放功能可能就会卡顿，如果不做缩放完全是OK的。

**Comment by popking5466** [comment]
目前需求是不需要做缩放功能,所以我会把您的缩放功能静默,数据量不会很大,也就24 * 7个数据

**Comment by popking5466** [comment]
目前需求是不需要做缩放功能,所以我会把您的缩放功能静默,数据量不会很大,也就24 * 7个数据,
您这个库功能已经十分完全,是否能在基础上加入page功能,或者,如果不用scrollView去做,是否还有其他思路

**Comment by popking5466** [comment]
目前需求是不需要做缩放功能,所以我会把您的缩放功能静默,数据量不会很大,也就24 * 7个数据,
您这个库功能已经十分完全,是否能在基础上加入page功能,或者,如果不用scrollView去做,是否还有其他思路

有一个类似于xswipestep的常量,去控制滑动的x单位坐标

**Comment by popking5466** [comment]
目前需求是不需要做缩放功能,所以我会把您的缩放功能静默,数据量不会很大,也就24 * 7个数据,
您这个库功能已经十分完全,是否能在基础上加入page功能,或者,如果不用scrollView去做,是否还有其他思路

有一个类似于xswipestep的常量,去控制滑动的x单位坐标 并且有scrollview的效果

**Comment by cslmark** [comment]
单纯加上一个scrollerView的功能的Page功能，其实也简单，只是一来这个功能和目前的功能有些冲突什么时候使能滑动的单位设置呢， 二来就是如果 就是要等我有时间。虽然容易，确实也好花点时间封装下。

**Comment by qiuseruxin** [comment]
大神 可以画横线做阀值吗  比如我想画两条平行于X轴的横线 一条做高血糖阀值  一条做低血糖阀值

**Comment by cslmark** [comment]
可以 @qiuseruxin 
 的这个需求，还有 @popking5466 的需求都不难，不过这段时间没有时间帮你们加。。周五、周六帮你们更新上！

**Comment by qiuseruxin** [comment]
感谢大神
![cd697f5e3f826ae8050e54355888ce1f](https://user-images.githubusercontent.com/19419747/27854555-d2e3bcee-6199-11e7-954d-d80d2d13341f.jpg)
我现在已经做到这个地步了

**Comment by cslmark** [comment]
好看，给你点赞！

**Comment by cslmark** [comment]
已经在mulCur的分支上增加阈值线的功能 @qiuseruxin  pageScroller模仿了下，不过说实话，效果确实不佳，统计图标增加这种功能，感觉效果确实不好。 @popking5466 
最近忙，更新晚了！

**Comment by qiuseruxin** [comment]
在下Xcode打字员  感谢大神!

**Comment by popking5466** [comment]
Thx so much!!

**Comment by qiuseruxin** [comment]
大佬，可以在坐标系里标记红点吗？我这边的需求是这样，假如我们仪器测出用户的血糖在 2点钟是12，那在曲线上就是横坐标  2点 纵坐标  12，然后在用户自己用试纸测量的时候测出2点其实是16血糖的时候，我想在横坐标2点钟，纵坐标16处标记一个小红点，这个红点也有可能在曲线上（用户试纸测的和设备测的一样）

**Comment by cslmark** [comment]
可以增加。。。关键是 你的红点增加的逻辑，你这么描述让我很费解呀。

**Comment by qiuseruxin** [comment]
额，就是在坐标系里任意位置增加红点。。。
________________________________
发件人: 陈双林<mailto:notifications@github.com>
发送时间: ‎2017/‎8/‎3 11:31
收件人: cslmark/SLCurveChartLib<mailto:SLCurveChartLib@noreply.github.com>
抄送: Anna<mailto:qiuseruxin@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [cslmark/SLCurveChartLib] 请问怎么加快滑动速度呢 (#6)


可以增加。。。关键是 你的红点增加的逻辑，你这么描述让我很费解呀。

**Comment by qiuseruxin** [comment]
额，就是在坐标系里任意位置增加红点。。。

**Comment by qiuseruxin** [comment]
大佬 有设置y轴从0开始的方法吗。数据刚开始时是负值 但不想让他在曲线上显示

**Comment by cslmark** [comment]
y轴从0开始的，那那些负数的点，你打算如何展示，其一。。。其二，增加红点，与其说你你的需求是任何位置增加红点，还不如说你你需要怎么样的接口给你调用呢！

**Comment by qiuseruxin** [comment]
负数只在曲线刚开始时存在，一旦曲线有值之后就不会再有负数了，所以想不展示负数。红点那个希望我传一个横坐标和纵坐标的值，这样可以吗大佬，还有就是大佬我发现当y轴的数据全是0的时候会出现问题，直接死机了。
