### ISSUE TITLE
如何自定义X轴 Y轴的间隔

### ISSUE THREAD

**Issue by pengwanwan** [cslmark/SLCurveChartLib#8]

**Comment by cslmark** [comment]
https://github.com/cslmark/SLCurveChartLib/issues/7
首先请你先阅读下这个issue，其次给个提示，Y轴的间距为 Y轴的代理方法中返回对应的等分
X轴的间距，可以设置属性，当前屏幕一屏幕显示多少个点来确定，希望帮到你

**Comment by pengwanwan** [comment]
感谢感谢




发自网易邮箱大师
在2017年07月05日 20:46，陈双林 写道：

#7
首先请你先阅读下这个issue，其次给个提示，Y轴的间距为 Y轴的代理方法中返回对应的等分
X轴的间距，可以设置属性，当前屏幕一屏幕显示多少个点来确定，希望帮到你

**Comment by pengwanwan** [comment]
我是想知道自定义坐标轴上  单位间隔的快读，而不是小格子的条数，我还没有找到可以设置的属性，麻烦作者有空截图一下




发自网易邮箱大师
在2017年07月05日 20:48，pengwanwan 写道：
感谢感谢




发自网易邮箱大师
在2017年07月05日 20:46，陈双林 写道：

#7
首先请你先阅读下这个issue，其次给个提示，Y轴的间距为 Y轴的代理方法中返回对应的等分
X轴的间距，可以设置属性，当前屏幕一屏幕显示多少个点来确定，希望帮到你

**Comment by pengwanwan** [comment]
单位间隔的宽度




发自网易邮箱大师
在2017年07月05日 21:21，pengwanwan 写道：
我是想知道自定义坐标轴上  单位间隔的快读，而不是小格子的条数，我还没有找到可以设置的属性，麻烦作者有空截图一下




发自网易邮箱大师
在2017年07月05日 20:48，pengwanwan 写道：
感谢感谢




发自网易邮箱大师
在2017年07月05日 20:46，陈双林 写道：

#7
首先请你先阅读下这个issue，其次给个提示，Y轴的间距为 Y轴的代理方法中返回对应的等分
X轴的间距，可以设置属性，当前屏幕一屏幕显示多少个点来确定，希望帮到你

**Comment by cslmark** [comment]
<img width="774" alt="wx20170705-213155 2x" src="https://user-images.githubusercontent.com/13198159/27866551-68fe8ce8-61c9-11e7-9454-6e22dc34f88a.png">
@pengwanwan  不好意思让你失望了，没有你想要的方法的API开发，不过对你而言密度和份数有什么差别吗。如果想设置密度为 20 ，总长度假定为100 设置份数为5就是了，不同型号的手机只是总长度不一致，以此类推乘上一个系数！

**Comment by pengwanwan** [comment]
你好 请问画线部分，能不能做到前一个点与后一个点的连接，然后形成一条线，而不是一次就把这条线的数据全部画出来，
因为我们的需求是，一边画线一边获取下一个数据。

**Comment by SingleSun** [comment]
X轴坐标可以是日期类型的字符串么,该怎么修改
